### ISSUE TITLE
Abort Jenkins based load test

### ISSUE THREAD

**Issue by mo-gr** [zalando-incubator/docker-locust#27]
When running locust as a Jenkins job (as described in the readme), aborting the Jenkins job does not actually abort the running load test.

All the spawned docker containers are still running after the job has been canceled and they still create load.

It would be great, if aborting the Jenkins job would also abort the running load test.

I see three approaches how this could work:
1. intercept the signal sent from jenkins for aborting and do some cleanup
2. provide a how-to for a post-build action that does the cleanup if necessary 
3. also spawn a watchdog, that checks if the job is still running and that will cleanup (including itself) after the job has been cancelled

I think, 1. would be the best, and 2. probably the easiest

**Comment by butomo1989** [comment]
Fixed. it will work also for local machine.
