### ISSUE TITLE
Where can I verify that the Locust tasks were run against the Target URL?

### ISSUE THREAD

**Issue by mccrodp** [zalando-incubator/docker-locust#7]
Hey, thanks for this repo, all looks great and seems to be functioning well.

I have a html report, I can access the CSV files also. However, I cannot verify that the tests were run against my Target URL. Is there an indicator to state what the tests were run against? i.e - that they weren't just run against `/` or `localhost` on the same machine.

I set the URL initially, but afterwards there is no indicator I can see. When I echo out `$TARGET_HOST`, `$TARGET_URL` and `$TARGET' I'm getting a blank also.

Thanks.

**Comment by butomo1989** [comment]
Hi @mccrodp ,

there are 2 ways to do it:
1. the $TARGET_URL will be passed only to ["master"](https://github.com/zalando-incubator/docker-locust/blob/master/docker-compose.yaml#L10) and ["slave"](https://github.com/zalando-incubator/docker-locust/blob/master/docker-compose.yaml#L21) container, you need to access one of those running containers and echo out target host by using: docker exec <container-name> echo $TARGET_HOST.
2. or you can modify the [load test script ](https://github.com/zalando-incubator/docker-locust/blob/master/example/simple.py#L16) to self.client.get('/', name='{target}/'.format(target=os.getenv('TARGET_HOST')))
